### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Ylinen** [nelinory/myForecast#1]
I entered the API Key and the location code per instructions.  Now I get this error:  Ooops-catastropic error.  Please, check the log file for more details.  Where is the log file?

**Comment by Ylinen** [comment]
Ok,  found the log file.  Here is the entry.  Greek to me.

01/21/2016 15:10:40.806     Error       Input string was not in a correct format.
Stack:   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at myForecast.WeatherModel.LoadCurrentConditionProperties(XmlNode currentConditionNode)
   at myForecast.WeatherModel.LoadWeatherModel()
   at myForecast.WeatherModel.LoadWeatherData()q2

**Comment by Ylinen** [comment]
deleted the cfm xml file and tried again.  Same error.

Here is my API Key: XXXXXXXXXXXX (edited by nelinory: Please, keep your key secret)

Here is my location ID: zmw:20121.1.99999

Please advise.

**Comment by Ylinen** [comment]
also tried API Key: XXXXXXXXXXXXXX-myForecast  (edited by nelinory: Please, keep your key secret)

**Comment by Ylinen** [comment]
Ok,  figured it out.  The location key was missing a "."

**Comment by nelinory** [comment]
Hi Ylinen, I am glad you found a solution. Based on your comments I have updated the README.md file to show where is the location of the myForecast generated files including the error log files.
