### ISSUE TITLE
Any plans to use the "hourly" forecast feature?

### ISSUE THREAD

**Issue by barnabas1969** [nelinory/myForecast#2]
Hi Chavdar,

Do you think you might be able to add the hourly forecast to this app?  I am curious why you instructed people in your readme to get the "Cumulus" plan for the API key, instead of the next one up that includes hourly forecasts.  I understand that you would need to add this feature to your program, but it seems reasonable to instruct people to get the higher plan... just in case you add the feature in the future.

Personally, I would love to see the hourly forecast.  I envision it working in a way so that I can click on a day that is displayed in your app, and the hourly forecast will be displayed... possibly allowing me to scroll left/right using the arrow keys to see the entire day.

Thanks for your work!  It's a nice app.  I'm running on Win 7 x64.

**Comment by nelinory** [comment]
Hello barnabas1969,

The reason I suggested the "Cumulus" plan is to be able to get the hourly forecast for the <b>current day</b>. Probably I bit short vision on my side although you can easily upgrade your existing WeatherUnderground key to the max level for free (500 calls limit stays). I was thinking on the idea to somehow show the hourly forecast for the current day without too much clutter - UI interface design is not my strong side ;)

I will take into consideration your suggestion (hourly forecast for each of the six days shown) for future release.

**Comment by barnabas1969** [comment]
Chavdar,

Thank you so much for your reply!  Do you have an Android (or Apple) phone?  If so, please install the Weather Underground app.  In the app, you can scroll down and tap any day in the forecast to see the hourly information for that day.  It would be magnificent if your Media Center app allowed the same functionality.

I am certain that you could duplicate the UI of the Android/iOS app.  In those apps, the hourly display shows a linear graph of temperature, wind speed/direction, precipitation percentages, and icons that represent things like sunny, partly cloudy, etc.

It would be wonderful if your program showed those... and in order to show more detail, it would be nice if the current-hour is shown on-screen, with the ability to scroll left/right using the arrow keys on the remote and/or keyboard.

**Comment by nelinory** [comment]
@barnabas1969 See issue #7 for the current outgoing discussion regarding current day forecast/hourly forecast.
