### ISSUE TITLE
Add option to place on start screen? [enhancement]

### ISSUE THREAD

**Issue by SinSharks** [nelinory/myForecast#3]
Hello, I would like to suggest adding the ability to access your app from the start screen of windows media center.

**Comment by barnabas1969** [comment]
SinSharks,

There are tools that will allow you to change the menus in Media Center.  You should go to www.thegreenbutton.tv.  Search there.  If you don't find a method to change the menus, post a question on that site.  I am certain that someone will respond with information about how to do it.

**Comment by nelinory** [comment]
This currently is implemented in the following way. After install of myForecast application there will be two start entries in Windows Media Center:
- Under "Extras" menu strip - this is the default and recommended location by Microsoft
- A menu strip named "Weather" will show up below "Extras" menu strip which will have myForecast application tile

Hiding/showing the new "Weather" menu strip can be managed through the new settings option inside myForecast settings screen.
