### ISSUE TITLE
Integrate into start menu - does not work correctly.

### ISSUE THREAD

**Issue by barnabas1969** [nelinory/myForecast#6]
Hi Chavdar,

I just downloaded version 1.0.1, and the new option to integrate the shortcut into the Start Menu does not work correctly.  I have modified my start menu slightly, so I'm wondering if this might be the problem.  What I get when I select the option is a new strip titled "Weather", which simply contains the same items that are in my TV menu, which is customized by Recorded TV HD.  I'll attach a screenshot.

![weather](https://cloud.githubusercontent.com/assets/5233162/12830461/7092916a-cb5d-11e5-9c89-85a42f1c0355.jpg)
![tv](https://cloud.githubusercontent.com/assets/5233162/12830460/7090b660-cb5d-11e5-8bf8-c1309459acfb.jpg)

**Comment by nelinory** [comment]
Hello barnabas1969,

This is an interesting issue. When I tested the start menu functionality on the both media center instances I have the new Weather strip actually shows below "Extras" strip like the screenshot here: https://msdn.microsoft.com/en-us/library/windows/desktop/bb189043.aspx. I will investigate this and will keep you updated.

**Comment by nelinory** [comment]
Hello @barnabas1969 ,

After some experiments on my development Windows Media Center box I have made a patch for you - hopefully it works. It seems the process of modifying the start menu tiles is finicky.

Patch install steps:
- Close Windows Media Center application
- Download the following patch file: https://github.com/nelinory/myForecast/releases/download/v1.0.1/myForecastStartMenuPatch.zip
- Extract the patch file content to C:\Program Files (x86)\Nelinory\MyForecast (my Forecast install folder)
- Right click on the PatchInstall.bat and select "Run as administrator"
- Start Windows Media Center application and check if the myForecast start menu strip is fixed
- In case the fix does not work, please close Windows Media Center application, right click on the PatchUninstall.bat and select "Run as administrator"

**Comment by nelinory** [comment]
The fix was committed to the master branch.
