### ISSUE TITLE
Current day forecast/hourly forecast UI mock ups

### ISSUE THREAD

**Issue by nelinory** [nelinory/myForecast#7]
**02/16/16 Updates based on the feedback from http://www.thegreenbutton.tv and GitHub**

![myforecast_i](https://cloud.githubusercontent.com/assets/15143882/13093946/95a6f5e4-d4cd-11e5-8ccb-b9cf4bec6515.png)
#### General
- Centered the whole layout
- Cleaned up the temperature data on the screen. Now it shows the correct unit - °F/°C
#### Current weather condition
- Removed the decimal point for the temperature
#### Current day forecast - left tile
- The title is dynamically build now as follows:

```
If Hour >= 0 AND Hour < NOON -> TODAY
If Hour >= NOON AND Hour < 8PM  -> TONIGHT
If Hour >= 8 PM AND Hour < MIDNIGHT -> TOMORROW
```
- **The WeatherUnderground API only gives the evening forecast for the current day regardless of when you have requested the data**. Currently the tile shows the information 2 hours ahead of time from the hourly forecast weather data. Example: in the above screenshot the current forecast will shows the weather forecast data for 12:53 AM.
- Daily forecast - now shows only 5 days forecast

![myforecast_ii](https://cloud.githubusercontent.com/assets/15143882/13094699/083b84a4-d4d2-11e5-89c5-b26f0c336046.png)
#### Hourly data visualization
- You can now navigate to the current weather condition panel - when selected it acts as a button. Once you click it you can see one of the following two use cases.

![myforecast_iia](https://cloud.githubusercontent.com/assets/15143882/13094746/6f21156c-d4d2-11e5-9e6c-b6be1ec6b72f.png)
#### Hourly data visualization - Use case I
- Navigates to a new page and shows the 36 hours of forecast weather data. You can use the left/right button on the remote control to scroll thru the data.

![myforecast_iib](https://cloud.githubusercontent.com/assets/15143882/13094800/c655c206-d4d2-11e5-8234-823f97bda60e.png)
#### Hourly data visualization - Use case II :yum:
- Hides the daily forecast data and shows the 36 hours of forecast weather data. You can use the left/right button on the remote control to scroll thru the data. To go back to the default layout just click again on the current weather condition panel. The scheduled data refresh will also restore default layout.

**Comment by barnabas1969** [comment]
Chavdar,

I was thinking of something similar to the Weather Underground app for Android.  It doesn't display the hourly data unless you tap on the daily forecast panel.  Can you make your app do something similar?  Can the daily panels display the same data they do today... AND also be "buttons" that can be clicked with the keyboard/mouse/remote-control?

Then, once the daily panel is clicked... display detailed hourly information, similar to the Android app.

Thanks.

**Comment by nelinory** [comment]
Updated the main storyboard based on the current feedback.

**Comment by Ylinen** [comment]
I like use case II. Show current weather at the top and then the hourly below.

**Comment by Embiggens** [comment]
Another vote for use case 2. I like the button suggestion and the case 2 implementation scheme is nice. Looks great!
