### ISSUE TITLE
Hourly forecast

### ISSUE THREAD

**Issue by barnabas1969** [nelinory/myForecast#8]
Hi Chavdar,

I think you misunderstood my request.

The latest version causes the current weather pane to become a "button" that can be clicked... and clicking it takes me to an hourly list of more buttons.

What I was asking for was to be able to click current AND future days... and after clicking one of those days... I would like to see the detail that I see on my Android phone.

Do you have an Android phone?  If so, please install the Weather Underground app and explore it by tapping on everything.  The iOS app for Weather Underground is probably very similar to the Android app.

**Comment by nelinory** [comment]
Hello @barnabas1969 ,

Windows Media Center platform is build as an entertainment center with DVR capabilities. It has a simple and clean interface which is designed to be manipulated by a remote control device or a mouse and shown on a normal TV screen.. After some experiments and feedback I do consider the current version of myForecast application to be a great compromise in regards of functionality and capabilities to show the weather data including the hourly forecast information and the way it is presented on the TV screen. If you would like to implement a different vision you are free to fork the source code.

Thank you.
